### ISSUE TITLE
Feature Request:  Limit number of Items per Column

### ISSUE THREAD

**Issue by BerndGit** [Totopolis/Kamban#1]
Hi. 

I like your tool. It is lightweight, offline and has good usability. Exactly what i was looking for. 

Feature request: 
- Disply sum of all items per column in header.
- Optionally one should be able to define a max limit of item for each individual column.

This would help to keep focused an not to overload oneself with issues.

Thanks, 
  BerndGit

**Comment by Totopolis** [comment]
We will add. 
May be any ideas about UI? (how these features can be setup)

**Comment by BerndGit** [comment]
Thanks Totopolis!

My idea:

*) Use contex menu (rigth click) on colum header to modify column properties.

*) Properties shall include selection of different behavoise:
     (a) no Limit, OR
     (b) Limit Warning, OR
     (c) Limit restiction 

In case of (b) & (c) a max number shall be added.


*) Behaviour in case on '(a) No Limit': 
- The Column header shall be extended showing also the total number of issues. (eg. 'ColumnName (5)')

*) Behaviour in case on '(b) Limit Warning': 
- The Column header shall be extended showing also the total number of issues and the max number (eg. 'ColumnName (5/10)')
- If max number of issues is exceeded the background color of the Header shall turn red
-> Benefit: no implications on look and feel. Users don't need to worry on warning messages. They can ignore or fix it.


*) Behaviour in case on '(c) Limit restriction': 
- The Column header shall be extended showing also the total number of issues and the max number (eg. 'ColumnName (5/10)')
- If max number of issues can not be exceeded.
- If you drag a card over a column which is already full:
       - The background turns dark grey, so you can visually see that you cannot drop here
       - If you try to drop. The card moves back to original position

- If you generate a new card (Strg-W):
      Column wich are already full are greyed-out. They are not available to be selected in the menu.

==== 
-> Benefit on these approches:
No need to make any pop-up messages, eg. "Max number exceeded", which could annoy the user. 


So far to my ideas. feel free to modify this, based on your experience. 



Thanks, BerndGit

**Comment by BerndGit** [comment]
Hi @Totopolis!

I have added the (b) Limit Warning in Pull request #6 
https://github.com/Totopolis/Kamban/pull/6

Greetings
   BerndGit
