### ISSUE TITLE
[Bug] moving Cards to new Rows

### ISSUE THREAD

**Issue by BerndGit** [Totopolis/Kamban#11]
Hi! 

Here comes your favourite software tester  :-)

(1) Generate a new Classic Board.

(2) Insert row before 'so-so', called 'intermediate'

(3) double click in 'Intermediate'/'Backlog' to generate new card.

-> You find out that card is generated in row 'Important' not as expected in the second row.

(4) realy move the card to row 'Intermediate

(5) Close the board, and see what happened in the database.

-> You'll find out that the the new card has:   ColumnID=1 (expected), RowId = 0 (Should be 2!!)

-> Similar bug can be found at insert columns

-> This discrepancy caused strange side effects, when applying the new feature from https://github.com/Totopolis/Kamban/pull/10 to new generated rows/columns

Greetings,
   Bernd

**Comment by Liklainy** [comment]
Thank you for opening an issue!
This issue was introduced with async auto-saving, disabled it for now.
Will try to refactor it in proper way and make it more explicit.

**Comment by BerndGit** [comment]
Thanks for fast fixing of the bug  @Liklainy !
