### ISSUE TITLE
Launch Issues

### ISSUE THREAD

**Issue by KyleKing** [Totopolis/Kamban#18]
I installed Kamban with chocolatey, but it won't launch. I tried running the Kamban.exe directly from a CMD prompt, but there was no STDOUT output and nothing appeared to happen

Is there a log file that would have useful information?

**Comment by Totopolis** [comment]
Hi. Sorry for delay. Yes, it is bug.
Please create folder "Kamban" in your roaming folder (C:\Users\YOU_USER\AppData\Roaming).
Log file will be there.
Fix update will be soon.

**Comment by KyleKing** [comment]
Thanks! That fixed it
