### ISSUE TITLE
Delete Bug still there

### ISSUE THREAD

**Issue by BerndGit** [Totopolis/Kamban#8]
Hello Totopolis,

Kindly note that your refactored code still suffers from issue #3 (at least when i compile on my side).

**Fast way to reproduce:**
(1) new board

(2) generate 3 new cards in one cell (A)

(3) delete the card on the top position

(4) move the lowest card to other cell (A) -> (B)

(5) move teh remaining card from (A) -> (B)

**How i could fix:**
In 
https://github.com/BerndGit/Kamban/commit/b7d6241e29d9d52b28297bee90f2da5c44dddef8
a simple update of REactiveUI and Dynamic data did the fix.

**However**
After your refactoring I cannot find the option to update the package anymore.

Kindly check, how to fix this. 
 
Thanks BerndGit

**Comment by Liklainy** [comment]
Thank you for opening an issue with this bug!  :)
DynamicData is a dependency for Ui.Wpf.Common, which is used for minimal Shell functionality.
https://github.com/gabbacode/WPF.Tools - Ui.Wpf.Common is an open source project and it's nuget is deployed to MyGet.
I will update dependencies in Ui.Wpf.Common.
For now, I specified DynamicData as a direct dependency with the latest version, which should fix it.

**Comment by BerndGit** [comment]
Thank you for explaination. 

closed.
